# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: C.Y. Tan's AstroPhotography Projects
email: cytan299@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
C.Y. Tan's AstroPhotography projects: field derotator, tribahtinov mask, ultimate home made dew shield, etx125 electric focuser, power distribution unit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cytan299.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cytan299

# Build settings
markdown: kramdown
kramdown: 
  input: GFM


gems:
  - jekyll-sitemap
  - jekyll-last-modified-at


